spring:
   datasource:
      url: jdbc:mysql://localhost:3306/accipiter3
      username: accipiter3
      password: accipiter3
      driver-class-name: com.mysql.jdbc.Driver
   mvc:
      static-path-pattern: /static/**
mybatis:
   mapper-locations: classpath*:mybatis/*Dao.xml
   type-aliases-package: com.monitor.video
   configuration:
       map-underscore-to-camel-case: true