spring:
   datasource:
      url: jdbc:mysql://192.168.1.34:3306/video
      username: root
      password: 48STX2X
      driver-class-name: com.mysql.jdbc.Driver
   mvc:
      static-path-pattern: /static/**
mybatis:
   mapper-locations: classpath*:mybatis/*Dao.xml
   type-aliases-package: com.monitor.video
   configuration:
       map-underscore-to-camel-case: true